// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PebbleJar.Infrastructure.Data;

#nullable disable

namespace PebbleJar.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PebbleJarDbContext))]
    [Migration("20260907010048_AlterTransactionsAddPersistentType")]
    partial class AlterTransactionsAddPersistentType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PebbleJar.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_number");

                    b.Property<int?>("ConnectionProvider")
                        .HasColumnType("INTEGER")
                        .HasColumnName("connection_provider");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Currency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("currency");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<Guid>("FinancialInstitutionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("financial_institution_id");

                    b.Property<bool>("IsSyncEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_sync_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("SourceFetchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_fetched_at");

                    b.Property<string>("SourcePayloadJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_payload_json");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("FinancialInstitutionId")
                        .HasDatabaseName("ix_accounts_financial_institution_id");

                    b.HasIndex("ConnectionProvider", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_connection_provider_external_id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("PebbleJar.Domain.FinancialInstitution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("ConnectionProvider")
                        .HasColumnType("INTEGER")
                        .HasColumnName("connection_provider");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_financial_institutions");

                    b.HasIndex("ExternalId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_financial_institutions_external_id_name");

                    b.ToTable("financial_institutions", (string)null);
                });

            modelBuilder.Entity("PebbleJar.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ExternalAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_account_id");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("SourceFetchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_fetched_at");

                    b.Property<string>("SourcePayloadJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_payload_json");

                    b.Property<string>("TransactionDateTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_date_time");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("AccountId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_account_id_external_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("PebbleJar.Domain.Account", b =>
                {
                    b.HasOne("PebbleJar.Domain.FinancialInstitution", "FinancialInstitution")
                        .WithMany("Accounts")
                        .HasForeignKey("FinancialInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_financial_institutions_financial_institution_id");

                    b.Navigation("FinancialInstitution");
                });

            modelBuilder.Entity("PebbleJar.Domain.Transaction", b =>
                {
                    b.HasOne("PebbleJar.Domain.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_accounts_account_id");

                    b.OwnsOne("PebbleJar.Domain.TransactionRecognitionData", "RecognitionData", b1 =>
                        {
                            b1.Property<Guid>("TransactionId");

                            b1.Property<string>("CardSuffix");

                            b1.Property<string>("Category");

                            b1.Property<string>("Code");

                            b1.Property<string>("CounterpartyAccount");

                            b1.Property<string>("Group");

                            b1.Property<string>("MerchantName");

                            b1.Property<string>("Particulars");

                            b1.Property<string>("Reference");

                            b1.HasKey("TransactionId");

                            b1.ToTable("transactions");

                            b1
                                .ToJson("recognition_data")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId")
                                .HasConstraintName("fk_transactions_transactions_id");
                        });

                    b.Navigation("Account");

                    b.Navigation("RecognitionData");
                });

            modelBuilder.Entity("PebbleJar.Domain.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PebbleJar.Domain.FinancialInstitution", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
