// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PebbleJar.Infrastructure.Data;

#nullable disable

namespace PebbleJar.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PebbleJarDbContext))]
    [Migration("20260825031154_AddFinancialInstitutions")]
    partial class AddFinancialInstitutions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PebbleJar.Domain.FinancialInstitution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_financial_institutions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_financial_institutions_name");

                    b.ToTable("financial_institutions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
