@PebbleJar.Api_HostAddress = http://localhost:5142

### Health check
GET {{PebbleJar.Api_HostAddress}}/health/
Accept: application/json

### Accounts
GET {{PebbleJar.Api_HostAddress}}/accounts/
Accept: application/json

### Transactions
GET {{PebbleJar.Api_HostAddress}}/transactions/
Accept: application/json


